---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-approve
  annotations:
    render.crossplane.io/runtime: Development
spec:
  package: xpkg.upbound.io/upbound/function-approve:v0.1.0
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-patch-and-transform
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.2.1