apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: group-membership-example-context-ref
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: environmentConfigs
      functionRef:
        name: crossplane-contrib-function-environment-configs
      input:
        apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
        kind: Input
        spec:
          environmentConfigs:
            - type: Reference
              ref:
                name: example-config
    - step: get-group-members
      functionRef:
        name: function-msgraph
      input:
        apiVersion: msgraph.fn.crossplane.io/v1alpha1
        kind: Input
        queryType: GroupMembership
        groupRef: context.[apiextensions.crossplane.io/environment].group.name
        # The function will automatically select standard fields:
        # - id, displayName, mail, userPrincipalName, appId, description
        target: "status.groupMembers"
        skipQueryWhenTargetHasData: true
      credentials:
        - name: azure-creds
          source: Secret
          secretRef:
            namespace: upbound-system
            name: azure-account-creds
