apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: group-objectids-example-spec-ref
  annotations:
    # Important: This function requires an Azure AD app registration with Microsoft Graph API permissions:
    # - Group.Read.All
    # - Directory.Read.All
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: get-group-objectids
      functionRef:
        name: function-msgraph
      input:
        apiVersion: msgraph.fn.crossplane.io/v1alpha1
        kind: Input
        queryType: GroupObjectIDs
        # Using spec reference to get group names
        groupsRef: "spec.groupConfig.names"
        target: "status.groupObjectIDs"
        skipQueryWhenTargetHasData: true
      credentials:
        - name: azure-creds
          source: Secret
          secretRef:
            namespace: upbound-system
            name: azure-account-creds