apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: group-membership-example
  annotations:
    # Important: This function requires an Azure AD app registration with Microsoft Graph API permissions:
    # - Group.Read.All
    # - Directory.Read.All
    # - User.Read.All (if groups contain users)
    # - Application.Read.All (if groups contain service principals)
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: get-group-members
      functionRef:
        name: function-msgraph
      input:
        apiVersion: msgraph.fn.crossplane.io/v1alpha1
        kind: Input
        queryType: GroupMembership
        group: test-fn-msgraph
        # The function will automatically select standard fields:
        # - id, displayName, mail, userPrincipalName, appId, description
        target: "status.groupMembers"
        skipQueryWhenTargetHasData: true
      credentials:
        - name: azure-creds
          source: Secret
          secretRef:
            namespace: upbound-system
            name: azure-account-creds
