apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: group-objectids-example-context-ref
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: environmentConfigs
      functionRef:
        name: crossplane-contrib-function-environment-configs
      input:
        apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
        kind: Input
        spec:
          environmentConfigs:
            - type: Reference
              ref:
                name: example-config
    - step: get-group-objectids
      functionRef:
        name: function-msgraph
      input:
        apiVersion: msgraph.fn.crossplane.io/v1alpha1
        kind: Input
        queryType: GroupObjectIDs
        groupsRef: context.[apiextensions.crossplane.io/environment].groups
        target: "status.groupObjectIDs"
        skipQueryWhenTargetHasData: true
      credentials:
        - name: azure-creds
          source: Secret
          secretRef:
            namespace: upbound-system
            name: azure-account-creds
