apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: service-principal-example-status-ref
  annotations:
    # Important: This function requires an Azure AD app registration with Microsoft Graph API permissions:
    # - Application.Read.All
    # - Directory.Read.All
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: get-service-principal-details
      functionRef:
        name: function-msgraph
      input:
        apiVersion: msgraph.fn.crossplane.io/v1alpha1
        kind: Input
        queryType: ServicePrincipalDetails
        servicePrincipalsRef: status.servicePrincipalNames
        target: "status.servicePrincipals"
        skipQueryWhenTargetHasData: true
      credentials:
        - name: azure-creds
          source: Secret
          secretRef:
            namespace: upbound-system
            name: azure-account-creds