apiVersion: example.crossplane.io/v1
kind: XApproval
metadata:
  name: approval-example
spec:
  resources:
    data:
      key1: value1
      key2: value2
      config: |
        # Example configuration
        port: 8080
        debug: true
        environment: development
status:
  approved: true
  currentHash: c48da99a2611a5c0ee7fcdf769a14307a2fbf4c6ec160f945c5837a0b5fc75bd
